version: 'v2.32.4'
services:
  api:
    build: ./api
    container_name: api
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
  ui:
    build: ./ui
    container_name: react-ui
    ports:
      - "3000:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true